#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcclient.h>
#include <wx/colordlg.h>>
#include <wx/wxprec.h>
#include <wx/dcbuffer.h>
#include "ReadInstructions.h"
/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void changed_size_window( wxUpdateUIEvent& event );
		void choose_file_ins( wxCommandEvent& event );
		void start_animation( wxCommandEvent& event );
		void touch( wxCommandEvent& event );
		std::string  _filename = "./Instructions.txt";
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

		void update_view();
		void Show_animation();
		int _radius = 20;
		wxBitmap _banan;
		wxImage picture;

};

#endif // __GUIMyFrame1__
