#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/dcclient.h>
#include <wx/colordlg.h>
#include <wx/wxprec.h>
#include <wx/dcbuffer.h>
#include "ReadInstructions.h"
#include <memory>
/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void choose_file_ins( wxCommandEvent& event );
		void start_animation( wxCommandEvent& event );
		void stop_animation( wxCommandEvent& event );
		void save_bitmap(wxCommandEvent& event);
		std::string  _filename = "";
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

		void Show_animation(bool save);
		ReadInstructions* read = nullptr;
		~GUIMyFrame1();
};

#endif // __GUIMyFrame1__
